version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  target-branch: 1-stable
  ignore:
  - dependency-name: berkshelf
    versions:
    - "> 4.3"
