# stub to call Ruby CI pipeline from main and release branches for 
# all application types (standard pipeline steps)
name: Run ci-all-ruby-main from chef/common-github-actions

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
      - 'releases/**'
      # - master
      # - develop
      # - 'features/**' 

  workflow_dispatch:
    # inputs:
    #   language:
    #     description: 'Primary language in the repository'
    #     required: true
    #     type: choice
    #     options: 
    #       - GoLang
    #       - Ruby
    #       - Rust
    #   outputfilename:
    #     description: 'Name of the SCC output file'
    #     required: false
    #     type: string
    #     default: 'scc-output.txt'
    #   message:
    #     required: true
    #     type: string

jobs: 
  call-ci-ruby-main-pipeline:
    uses: chef/common-github-actions/.github/workflows/ci-all-ruby-main.yml@main
    with:
      language: 'Ruby'
      outputfilename: 'scc-output.txt'
      # message: ${{ inputs.message }}
    secrets: inherit